title: Caroline et Laurent
description: Toutes les informations sur le mariage de Caroline et Laurent
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/logo.png
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Configuration des langues
languages: ["fr", "en", "de", "cn"]
default_lang: "fr"

descriptions:
  fr: "Toutes les informations sur le mariage de Caroline et Laurent"
  en: "All information about Caroline and Laurent's wedding"
  de: "Alle Informationen über die Hochzeit von Caroline und Laurent"
  cn: "关于 Caroline 和 Laurent 婚礼的所有信息"
